sudo: required
services:
    - docker
before_install:
    - docker build -t jsparmani/docker-production-workflow -f Dockerfile.dev .

script:
    - docker run jsparmani/docker-production-workflow npm run test -- --coverage